server.port: 8080

spring:
  profiles:
    active: local
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    templateResolverOrder: 1
  h2:
    console:
      enabled: true
      path: /h2